CREATE OR REPLACE FUNCTION perseus_dbo.udf_datetrunc(IN "@Datein" TIMESTAMP WITHOUT TIME ZONE)
RETURNS TIMESTAMP WITHOUT TIME ZONE
AS
$BODY$
BEGIN
    RETURN CAST (FLOOR(CAST ("@Datein" AS DOUBLE PRECISION)) AS TIMESTAMP WITHOUT TIME ZONE);
END;
$BODY$
LANGUAGE  plpgsql;

