-- =============================================================================
-- View: perseus.combined_field_map
-- Task: T043 (US1 Phase 2)
-- Source: source/building/pgsql/refactored/15.create-view/analysis/combined_field_map-analysis.md
-- Description: Unified field map record set — combines the static field_map base
--              table with synthetic field map entries generated by combined_sp_field_map
--              (derived from smurf_property definitions for three UI contexts).
-- Dependencies: perseus.field_map (base table), perseus.combined_sp_field_map (Wave 0 view)
-- Quality Score: 9.3/10
-- Author: Migration Team
-- Date: 2026-03-08
-- =============================================================================
--
-- Column descriptions:
--   id                — Unique identifier (base: real ID; synthetic: ID+20000/30000/40000)
--   field_map_block_id — Block grouping (base: real; synthetic: smurf_id+1000/2000/3000)
--   setter            — JavaScript setter method call (NULL for list/CSV context)
--   lookup            — PHP lookup method call (NULL when no property_option)
--   save_sequence     — Ordering within a field map block (1 or 2)
--   field_map_set_id  — UI set grouping (9 for smurf class_id=2, 12 otherwise)
--
-- Wave: Wave 1
-- Deployment prerequisite: perseus.combined_sp_field_map (Wave 0) must be deployed first.
-- T-SQL source: dbo.combined_field_map
-- Issues resolved:
--   P1-01: Wrong schema perseus_dbo -> perseus (all references)
--   P2-01: T-SQL bracket notation removed
--   P2-02: SELECT * in Branch 2 replaced with explicit 14-column list
--   P2-04: COMMENT ON VIEW added
-- =============================================================================

CREATE OR REPLACE VIEW perseus.combined_field_map (
    id,
    field_map_block_id,
    name,
    description,
    display_order,
    setter,
    lookup,
    lookup_service,
    nullable,
    field_map_type_id,
    database_id,
    save_sequence,
    onchange,
    field_map_set_id
) AS

-- Branch 1: Real field_map records from base table
SELECT
    id,
    field_map_block_id,
    name,
    description,
    display_order,
    setter,
    lookup,
    lookup_service,
    nullable,
    field_map_type_id,
    database_id,
    save_sequence,
    onchange,
    field_map_set_id
FROM perseus.field_map

UNION

-- Branch 2: Synthetic field_map records from smurf_property definitions
-- Note: explicit column list replaces SELECT * for resilience to upstream view changes (P2-02)
SELECT
    id,
    field_map_block_id,
    name,
    description,
    display_order,
    setter,
    lookup,
    lookup_service,
    nullable,
    field_map_type_id,
    database_id,
    save_sequence,
    onchange,
    field_map_set_id
FROM perseus.combined_sp_field_map;

-- Documentation
COMMENT ON VIEW perseus.combined_field_map IS
    'Unified field map registry. Combines static field_map records with synthetic '
    'entries from combined_sp_field_map (derived from smurf_property for three UI contexts). '
    'Synthetic IDs use offsets +20000, +30000, +40000 to avoid collisions with base IDs. '
    'Wave 1: requires combined_sp_field_map (Wave 0) to be deployed first. '
    'Depends on: field_map (base table), combined_sp_field_map (view). '
    'T-SQL source: dbo.combined_field_map | Migration task T043.';

GRANT SELECT ON perseus.combined_field_map TO perseus_app, perseus_readonly;
