CREATE OR REPLACE FUNCTION perseus_dbo.fn_tr_syssubscriptions_biu()
RETURNS trigger
AS
$BODY$
BEGIN
    IF ((TG_OP = 'INSERT' AND NEW.timestamp IS NOT NULL) OR (TG_OP = 'UPDATE' AND NEW.timestamp <> OLD.timestamp)) THEN
        RAISE EXCEPTION 'The column "timestamp" cannot be modified because it is an autogenerated column ';
    END IF;
    NEW.timestamp := nextval('aws_sqlserver_ext_data.inc_seq_rowversion');
    RETURN NEW;
END
$BODY$
LANGUAGE  plpgsql;

