DROP ROUTINE IF EXISTS perseus_dbo.getupstreamcontainers(OUT INTEGER, IN INTEGER, OUT INTEGER, IN TIMESTAMP WITHOUT TIME ZONE, OUT INTEGER, IN TIMESTAMP WITHOUT TIME ZONE, OUT VARCHAR, OUT INTEGER);

