DROP ROUTINE IF EXISTS perseus_dbo.getdownstreamcontainers(OUT INTEGER, IN INTEGER, OUT INTEGER, IN TIMESTAMP WITHOUT TIME ZONE, OUT INTEGER, IN TIMESTAMP WITHOUT TIME ZONE, OUT VARCHAR, OUT INTEGER);

