erDiagram
    Permissions {
        nvarchar emailAddress 
        char permission 
    }

    Scraper {
        char Active 
        bit Complete 
        int ControlFileID 
        nvarchar DocumentID 
        varbinary File 
        char FileType 
        nvarchar Filename 
        nvarchar FilenameSavedAs 
        int ID PK 
        nvarchar Message 
        nvarchar ReceivedFrom 
        nvarchar Result 
        nvarchar ScraperID 
        nvarchar ScraperMessage 
        nvarchar ScraperSendTo 
        datetime ScrapingFinishedOn 
        datetime ScrapingStartedOn 
        nvarchar ScrapingStatus 
        datetime Timestamp 
    }

    alembic_version {
        varchar version_num PK 
    }

    cm_application {
        int application_group_id 
        int application_id PK 
        varchar description 
        tinyint is_active 
        varchar jira_id 
        varchar label 
        int owner_user_id 
        varchar url 
    }

    cm_application_group {
        int application_group_id PK 
        varchar label 
    }

    cm_group {
        char domain_id 
        int group_id PK 
        bit is_active 
        smalldatetime last_modified 
        varchar name 
    }

    cm_project {
        smallint display_order 
        int group_id 
        bit is_active 
        varchar label 
        smallint project_id PK 
    }

    cm_unit {
        nvarchar description 
        int dimensions_id 
        numeric factor 
        int id PK 
        nvarchar longname 
        nvarchar name 
        numeric offset 
    }

    cm_unit_compare {
        int from_unit_id PK 
        int to_unit_id PK 
    }

    cm_unit_dimensions {
        numeric amount_of_substance 
        int default_unit_id 
        numeric electric_current 
        int id PK 
        numeric length 
        numeric luminous_intensity 
        numeric mass 
        nvarchar name 
        numeric thermodynamic_temperature 
        numeric time 
    }

    cm_user {
        char domain_id 
        nvarchar email 
        bit is_active 
        nvarchar login 
        nvarchar name 
        uniqueidentifier object_id 
        int user_id PK 
    }

    cm_user_group {
        int group_id PK 
        int user_id PK 
    }

    coa {
        int goo_type_id FK,UK 
        int id PK 
        varchar name UK 
    }

    coa_spec {
        int coa_id FK,UK 
        varchar equal_bound 
        int id PK 
        float lower_bound 
        float lower_equal_bound 
        int property_id FK,UK 
        int result_precision 
        float upper_bound 
        float upper_equal_bound 
    }

    color {
        nvarchar name PK 
    }

    container {
        int container_type_id FK 
        datetime created_on 
        int depth 
        int id PK 
        int left_id 
        float mass 
        varchar name 
        varchar position_name 
        varchar position_x_coordinate 
        varchar position_y_coordinate 
        int right_id 
        nvarchar scope_id 
        nvarchar uid 
    }

    container_history {
        int container_id FK 
        int history_id FK 
        int id PK 
    }

    container_type {
        int id PK 
        int is_equipment 
        int is_gooable 
        int is_parent 
        int is_restricted 
        int is_single 
        varchar name UK 
    }

    container_type_position {
        int child_container_type_id FK 
        int id PK 
        int parent_container_type_id FK,UK 
        varchar position_name UK 
        varchar position_x_coordinate 
        varchar position_y_coordinate 
    }

    display_layout {
        int id PK 
        varchar name UK 
    }

    display_type {
        int id PK 
        varchar name UK 
    }

    external_goo_type {
        varchar external_label UK 
        int goo_type_id FK 
        int id PK 
        int manufacturer_id FK,UK 
    }

    fatsmurf {
        int added_by 
        datetime added_on 
        int container_id FK 
        varchar description 
        float duration 
        int id PK 
        datetime inserted_on 
        varchar name 
        int organization_id FK 
        int recycled_bottoms_id 
        datetime run_complete 
        datetime run_on 
        int smurf_id FK 
        int themis_sample_id 
        int triton_task_id 
        nvarchar uid 
        datetime updated_on 
        int workflow_step_id FK 
    }

    fatsmurf_attachment {
        int added_by FK 
        datetime added_on 
        image attachment 
        varchar attachment_mime_type 
        varchar attachment_name 
        text description 
        int fatsmurf_id FK 
        int id PK 
    }

    fatsmurf_comment {
        int added_by FK 
        datetime added_on 
        nvarchar comment 
        int fatsmurf_id FK 
        int id PK 
    }

    fatsmurf_history {
        int fatsmurf_id FK 
        int history_id FK 
        int id PK 
    }

    fatsmurf_reading {
        int added_by FK 
        datetime added_on 
        int fatsmurf_id FK,UK 
        int id PK 
        varchar name UK 
    }

    feed_type {
        int added_by FK 
        datetime added_on 
        float correction_factor 
        text correction_method 
        text description 
        bit disabled 
        int id PK 
        varchar name 
        int updated_by_id FK 
        datetime updated_on 
    }

    field_map {
        varchar database_id 
        varchar description 
        int display_order 
        int field_map_block_id FK 
        int field_map_set_id FK 
        int field_map_type_id FK 
        int id PK 
        varchar lookup 
        varchar lookup_service 
        varchar name 
        int nullable 
        varchar onchange 
        int save_sequence 
        varchar setter 
    }

    field_map_block {
        varchar filter UK 
        int id PK 
        varchar scope UK 
    }

    field_map_display_type {
        varchar display 
        int display_layout_id FK 
        int display_type_id FK,UK 
        int field_map_id FK,UK 
        int id PK 
        int manditory 
    }

    field_map_display_type_user {
        int field_map_display_type_id UK 
        int id PK 
        int user_id FK,UK 
    }

    field_map_set {
        varchar color 
        int display_order 
        int id PK 
        varchar name 
        int size 
        int tab_group_id 
    }

    field_map_type {
        int id PK 
        varchar name UK 
    }

    goo {
        int added_by FK 
        datetime added_on 
        varchar catalog_label 
        int container_id FK 
        varchar description 
        int goo_type_id FK 
        int id PK 
        datetime inserted_on 
        int manufacturer_id FK 
        varchar name 
        float original_mass 
        float original_volume 
        smallint project_id 
        date received_on 
        int recipe_id FK 
        int recipe_part_id FK 
        int triton_task_id 
        nvarchar uid 
        datetime updated_on 
        int workflow_step_id FK 
    }

    goo_attachment {
        int added_by FK 
        datetime added_on 
        image attachment 
        varchar attachment_mime_type 
        varchar attachment_name 
        varchar description 
        int goo_attachment_type_id FK 
        int goo_id FK 
        int id PK 
    }

    goo_attachment_type {
        int id PK 
        varchar name UK 
    }

    goo_comment {
        int added_by FK 
        datetime added_on 
        varchar category 
        text comment 
        int goo_id FK 
        int id PK 
    }

    goo_history {
        int goo_id FK 
        int history_id FK 
        int id PK 
    }

    goo_process_queue_type {
        int id PK 
        varchar name UK 
    }

    goo_type {
        varchar abbreviation 
        varchar casrn 
        varchar color 
        float density_kg_l 
        int depth 
        int disabled 
        int id PK 
        varchar iupac 
        int left_id UK 
        varchar name UK 
        int right_id UK 
        nvarchar scope_id UK 
    }

    goo_type_combine_component {
        int goo_type_combine_target_id FK,UK 
        int goo_type_id FK,UK 
        int id PK 
    }

    goo_type_combine_target {
        int goo_type_id FK 
        int id PK 
        int sort_order 
    }

    history {
        datetime created_on 
        int creator_id FK 
        int history_type_id FK 
        int id PK 
    }

    history_type {
        varchar format 
        int id PK 
        varchar name UK 
    }

    history_value {
        int history_id FK 
        int id PK 
        varchar value 
    }

    m_downstream {
        nvarchar end_point PK 
        int level 
        varchar path PK 
        nvarchar start_point PK 
    }

    m_number {
        int id 
    }

    m_upstream {
        nvarchar end_point PK 
        int level 
        varchar path PK 
        nvarchar start_point PK 
    }

    m_upstream_dirty_leaves {
        varchar material_uid 
    }

    manufacturer {
        varchar goo_prefix 
        int id PK 
        varchar location UK 
        varchar name UK 
    }

    material_inventory {
        int allocation_container_id FK 
        text comment 
        int created_by_id FK 
        datetime created_on 
        real current_mass_kg 
        real current_volume_l 
        date expiration_date 
        int id PK 
        bit is_active 
        int location_container_id FK 
        int material_id FK,UK 
        int recipe_id FK 
        int updated_by_id FK 
        datetime updated_on 
    }

    material_inventory_threshold {
        int created_by_id FK 
        datetime2 created_on 
        int id PK 
        int material_type_id FK,UK 
        int max_item_count 
        float max_mass_kg 
        float max_volume_l 
        int min_item_count 
        float min_mass_kg 
        float min_volume_l 
        int updated_by_id FK 
        datetime2 updated_on 
    }

    material_inventory_threshold_notify_user {
        int threshold_id PK,FK 
        int user_id PK,FK 
    }

    material_qc {
        text entity_type_name 
        int foreign_entity_id 
        int id PK 
        int material_id FK 
        text qc_process_uid 
    }

    material_transition {
        datetime added_on 
        nvarchar material_id PK,FK 
        nvarchar transition_id PK,FK 
    }

    migration {
        datetime created_on 
        varchar description 
        int id PK 
    }

    perseus_user {
        int admin 
        int common_id 
        varchar domain_id UK 
        int id PK 
        varchar login UK 
        varchar mail 
        int manufacturer_id FK 
        varchar name 
        int super 
    }

    person {
        char domain_id UK 
        varchar email 
        int id PK 
        bit is_active 
        char km_session_id 
        datetime last_login 
        nvarchar login 
        nvarchar name 
    }

    poll {
        int bounds_limit 
        int detection 
        int fatsmurf_reading_id FK,UK 
        int id PK 
        float limit_of_detection 
        float limit_of_quantification 
        float lower_calibration_limit 
        int smurf_property_id FK,UK 
        float standard_deviation 
        float upper_calibration_limit 
        varchar value 
    }

    poll_history {
        int history_id FK 
        int id PK 
        int poll_id FK 
    }

    prefix_incrementor {
        int counter 
        varchar prefix PK 
    }

    property {
        varchar description 
        int id PK 
        varchar name UK 
        int unit_id FK,UK 
    }

    property_option {
        int disabled 
        int id PK 
        varchar label UK 
        int property_id FK,UK 
        int value UK 
    }

    recipe {
        bit QC 
        int added_by FK 
        datetime added_on 
        varchar description 
        int feed_type_id FK 
        int goo_type_id FK 
        int id PK 
        float inoculant_percent 
        bit is_archived 
        bit is_preferred 
        varchar name UK 
        float post_inoc_volume_ml 
        varchar sop 
        varchar sterilization_method 
        float stock_concentration 
        int workflow_id FK 
    }

    recipe_part {
        float amount 
        varchar description 
        int goo_type_id FK 
        int id PK 
        int part_recipe_id FK 
        int position 
        int recipe_id FK 
        float target_conc_in_media 
        float target_post_inoc_conc 
        int unit_id FK 
        int workflow_step_id FK 
    }

    recipe_project_assignment {
        smallint project_id 
        int recipe_id FK 
    }

    robot_log {
        int class_id 
        datetime completed_on 
        datetime created_on 
        varchar file_name 
        int id PK 
        int loadable 
        int loaded 
        datetime loaded_on 
        varchar log_text 
        varchar robot_log_checksum 
        int robot_log_type_id FK 
        int robot_run_id FK 
        varchar source 
        datetime started_on 
    }

    robot_log_container_sequence {
        int container_id FK,UK 
        int id PK 
        datetime processed_on 
        int robot_log_id FK,UK 
        int sequence_type_id FK,UK 
    }

    robot_log_error {
        varchar error_text 
        int id PK 
        int robot_log_id FK 
    }

    robot_log_read {
        int id PK 
        int property_id FK 
        int robot_log_id FK 
        nvarchar source_barcode 
        int source_material_id FK 
        nvarchar source_position 
        varchar value 
    }

    robot_log_transfer {
        nvarchar destination_barcode 
        int destination_material_id FK 
        nvarchar destination_position 
        int id PK 
        int material_type_id 
        int robot_log_id FK 
        nvarchar source_barcode 
        int source_material_id FK 
        nvarchar source_position 
        datetime transfer_time 
        varchar transfer_volume 
    }

    robot_log_type {
        int auto_process 
        int destination_container_type_id FK 
        int id PK 
        varchar name UK 
    }

    robot_run {
        bit all_qc_passed 
        bit all_themis_submitted 
        int id PK 
        varchar name 
        int robot_id FK 
    }

    s_number {
        int id 
    }

    saved_search {
        int added_by FK,UK 
        datetime added_on 
        int class_id 
        int id PK 
        int include_downstream 
        int is_private 
        varchar name UK 
        varchar parameter_string 
    }

    sequence_type {
        int id PK 
        varchar name 
    }

    smurf {
        int class_id 
        varchar description 
        int disabled 
        int id PK 
        varchar name UK 
        int themis_method_id 
    }

    smurf_goo_type {
        int goo_type_id FK 
        int id PK 
        int is_input 
        int smurf_id FK 
    }

    smurf_group {
        int added_by FK 
        int id PK 
        int is_public 
        varchar name UK 
    }

    smurf_group_member {
        int id PK 
        int smurf_group_id FK,UK 
        int smurf_id FK,UK 
    }

    smurf_property {
        varchar calculated 
        int disabled 
        int id PK 
        int property_id FK,UK 
        int smurf_id FK,UK 
        int sort_order 
    }

    submission {
        datetime added_on 
        int id PK 
        varchar label 
        int submitter_id FK 
    }

    submission_entry {
        int assay_type_id FK 
        int id PK 
        int material_id FK 
        int prepped_by_id FK 
        varchar priority 
        varchar sample_type 
        varchar status 
        int submission_id FK 
        int themis_tray_id 
    }

    tmp_messy_links {
        varchar desitnation_name 
        nvarchar destination_transition 
        nvarchar material_id 
        varchar source_name 
        nvarchar source_transition 
    }

    transition_material {
        nvarchar material_id PK,FK 
        nvarchar transition_id PK,FK 
    }

    unit {
        varchar description 
        int dimension_id 
        float factor 
        int id PK 
        varchar name 
        float offset 
    }

    workflow {
        int added_by FK 
        datetime added_on 
        varchar category 
        varchar description 
        int disabled 
        int id PK 
        int manufacturer_id FK 
        varchar name UK 
    }

    workflow_attachment {
        int added_by FK 
        datetime added_on 
        varbinary attachment 
        varchar attachment_mime_type 
        varchar attachment_name 
        int id PK 
        int workflow_id FK 
    }

    workflow_section {
        int id PK 
        varchar name UK 
        int starting_step_id FK,UK 
        int workflow_id FK,UK 
    }

    workflow_step {
        float RECIPE_FACTOR 
        int child_order 
        int class_id 
        int depth 
        varchar description 
        int goo_amount_unit_id FK 
        int goo_type_id FK 
        int id PK 
        varchar label 
        int left_id 
        varchar name 
        tinyint optional 
        int parent_id 
        int property_id FK 
        int right_id 
        int scope_id FK 
        int smurf_id FK 
    }

    workflow_step_type {
        int id PK 
        varchar name UK 
    }

    coa }o--|| goo_type : "goo_type_id"
    coa_spec }o--|| coa : "coa_id"
    coa_spec }o--|| property : "property_id"
    container }o--|| container_type : "container_type_id"
    container_history }o--|| container : "container_id"
    fatsmurf }o--|| container : "container_id"
    goo }o--|| container : "container_id"
    material_inventory }o--|| container : "allocation_container_id"
    material_inventory }o--|| container : "location_container_id"
    robot_log_container_sequence }o--|| container : "container_id"
    robot_run }o--|| container : "robot_id"
    container_history }o--|| history : "history_id"
    container_type_position }o--|| container_type : "child_container_type_id"
    container_type_position }o--|| container_type : "parent_container_type_id"
    robot_log_type }o--|| container_type : "destination_container_type_id"
    field_map_display_type }o--|| display_layout : "display_layout_id"
    field_map_display_type }o--|| display_type : "display_type_id"
    external_goo_type }o--|| goo_type : "goo_type_id"
    external_goo_type }o--|| manufacturer : "manufacturer_id"
    fatsmurf }o--|| manufacturer : "organization_id"
    fatsmurf }o--|| smurf : "smurf_id"
    fatsmurf }o--|| workflow_step : "workflow_step_id"
    fatsmurf_attachment }o--|| fatsmurf : "fatsmurf_id"
    fatsmurf_comment }o--|| fatsmurf : "fatsmurf_id"
    fatsmurf_history }o--|| fatsmurf : "fatsmurf_id"
    fatsmurf_reading }o--|| fatsmurf : "fatsmurf_id"
    fatsmurf_attachment }o--|| perseus_user : "added_by"
    fatsmurf_comment }o--|| perseus_user : "added_by"
    fatsmurf_history }o--|| history : "history_id"
    fatsmurf_reading }o--|| perseus_user : "added_by"
    poll }o--|| fatsmurf_reading : "fatsmurf_reading_id"
    feed_type }o--|| perseus_user : "added_by"
    feed_type }o--|| perseus_user : "updated_by_id"
    recipe }o--|| feed_type : "feed_type_id"
    field_map }o--|| field_map_block : "field_map_block_id"
    field_map }o--|| field_map_set : "field_map_set_id"
    field_map }o--|| field_map_type : "field_map_type_id"
    field_map_display_type }o--|| field_map : "field_map_id"
    field_map_display_type_user }o--|| perseus_user : "user_id"
    goo }o--|| goo_type : "goo_type_id"
    goo }o--|| manufacturer : "manufacturer_id"
    goo }o--|| perseus_user : "added_by"
    goo }o--|| recipe : "recipe_id"
    goo }o--|| recipe_part : "recipe_part_id"
    goo }o--|| workflow_step : "workflow_step_id"
    goo_attachment }o--|| goo : "goo_id"
    goo_comment }o--|| goo : "goo_id"
    goo_history }o--|| goo : "goo_id"
    material_inventory }o--|| goo : "material_id"
    material_qc }o--|| goo : "material_id"
    robot_log_read }o--|| goo : "source_material_id"
    robot_log_transfer }o--|| goo : "destination_material_id"
    robot_log_transfer }o--|| goo : "source_material_id"
    submission_entry }o--|| goo : "material_id"
    goo_attachment }o--|| goo_attachment_type : "goo_attachment_type_id"
    goo_attachment }o--|| perseus_user : "added_by"
    goo_comment }o--|| perseus_user : "added_by"
    goo_history }o--|| history : "history_id"
    goo_type_combine_component }o--|| goo_type : "goo_type_id"
    goo_type_combine_target }o--|| goo_type : "goo_type_id"
    material_inventory_threshold }o--|| goo_type : "material_type_id"
    recipe }o--|| goo_type : "goo_type_id"
    recipe_part }o--|| goo_type : "goo_type_id"
    smurf_goo_type }o--|| goo_type : "goo_type_id"
    workflow_step }o--|| goo_type : "goo_type_id"
    goo_type_combine_component }o--|| goo_type_combine_target : "goo_type_combine_target_id"
    history }o--|| history_type : "history_type_id"
    history }o--|| perseus_user : "creator_id"
    history_value }o--|| history : "history_id"
    poll_history }o--|| history : "history_id"
    perseus_user }o--|| manufacturer : "manufacturer_id"
    perseus_user }o--|| manufacturer : "manufacturer_id"
    perseus_user }o--|| manufacturer : "manufacturer_id"
    workflow }o--|| manufacturer : "manufacturer_id"
    material_inventory }o--|| perseus_user : "created_by_id"
    material_inventory }o--|| perseus_user : "updated_by_id"
    material_inventory }o--|| recipe : "recipe_id"
    material_inventory_threshold }o--|| perseus_user : "created_by_id"
    material_inventory_threshold }o--|| perseus_user : "updated_by_id"
    material_inventory_threshold_notify_user }o--|| material_inventory_threshold : "threshold_id"
    material_inventory_threshold_notify_user }o--|| perseus_user : "user_id"
    recipe }o--|| perseus_user : "added_by"
    saved_search }o--|| perseus_user : "added_by"
    smurf_group }o--|| perseus_user : "added_by"
    submission }o--|| perseus_user : "submitter_id"
    submission_entry }o--|| perseus_user : "prepped_by_id"
    workflow }o--|| perseus_user : "added_by"
    workflow_attachment }o--|| perseus_user : "added_by"
    poll }o--|| smurf_property : "smurf_property_id"
    poll_history }o--|| poll : "poll_id"
    property }o--|| unit : "unit_id"
    property_option }o--|| property : "property_id"
    robot_log_read }o--|| property : "property_id"
    smurf_property }o--|| property : "property_id"
    workflow_step }o--|| property : "property_id"
    recipe }o--|| workflow : "workflow_id"
    recipe_part }o--|| recipe : "part_recipe_id"
    recipe_part }o--|| recipe : "recipe_id"
    recipe_project_assignment }o--|| recipe : "recipe_id"
    recipe_part }o--|| unit : "unit_id"
    recipe_part }o--|| workflow_step : "workflow_step_id"
    robot_log }o--|| robot_log_type : "robot_log_type_id"
    robot_log }o--|| robot_run : "robot_run_id"
    robot_log_container_sequence }o--|| robot_log : "robot_log_id"
    robot_log_error }o--|| robot_log : "robot_log_id"
    robot_log_read }o--|| robot_log : "robot_log_id"
    robot_log_transfer }o--|| robot_log : "robot_log_id"
    robot_log_container_sequence }o--|| sequence_type : "sequence_type_id"
    smurf_goo_type }o--|| smurf : "smurf_id"
    smurf_group_member }o--|| smurf : "smurf_id"
    smurf_property }o--|| smurf : "smurf_id"
    submission_entry }o--|| smurf : "assay_type_id"
    workflow_step }o--|| smurf : "smurf_id"
    smurf_group_member }o--|| smurf_group : "smurf_group_id"
    submission_entry }o--|| submission : "submission_id"
    workflow_step }o--|| unit : "goo_amount_unit_id"
    workflow_attachment }o--|| workflow : "workflow_id"
    workflow_section }o--|| workflow : "workflow_id"
    workflow_step }o--|| workflow : "scope_id"
    workflow_section }o--|| workflow_step : "starting_step_id"
