CREATE TABLE perseus_hermes.run(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    experiment_id INTEGER,
    local_id INTEGER,
    chart_legend VARCHAR(100),
    description CITEXT,
    strain CITEXT NOT NULL,
    resultant_material CITEXT,
    feedstock_material CITEXT,
    fermentation_type_id INTEGER,
    start_time TIMESTAMP WITHOUT TIME ZONE,
    induction_time NUMERIC(10,2),
    induction_od NUMERIC(10,2),
    stop_time NUMERIC(10,2),
    max_yield NUMERIC(15,5),
    max_productivity NUMERIC(15,5),
    max_titer NUMERIC(15,5),
    total_product NUMERIC(15,5),
    yield_calculator_state CITEXT,
    productivity_method NUMERIC(5,1),
    productivity_notes CITEXT,
    peak_titer_time NUMERIC(10,2),
    mfcs_file CITEXT,
    bioreactor_label CITEXT,
    shaker_ids CITEXT,
    platform_ids CITEXT,
    media_batch_label CITEXT,
    overlay_batch_label CITEXT,
    last_mfcs TIMESTAMP WITHOUT TIME ZONE,
    mfcs_status CITEXT,
    mfcs_status_time TIMESTAMP WITHOUT TIME ZONE,
    mfcs_status_message CITEXT,
    created_on TIMESTAMP WITHOUT TIME ZONE,
    updated_on TIMESTAMP WITHOUT TIME ZONE,
    max_updated_on TIMESTAMP WITHOUT TIME ZONE,
    tank CITEXT,
    fad_cycle INTEGER,
    creator_id INTEGER,
    updator_id INTEGER,
    max_updated_by_id INTEGER,
    protocol_id INTEGER,
    mfcs_user_id INTEGER,
    seed_vial_freeze_date TIMESTAMP WITHOUT TIME ZONE,
    volume_recovered NUMERIC(15,5),
    volume_missing NUMERIC(15,5),
    carbon_balance_method NUMERIC(5,1),
    carbon_balance NUMERIC(6,3),
    carbon_balance_state CITEXT,
    carbon_balance_user_id INTEGER,
    carbon_balance_date TIMESTAMP WITHOUT TIME ZONE,
    seed_vial_id INTEGER,
    yield_published NUMERIC(1,0),
    yield_publisher_id INTEGER,
    yield_publish_date TIMESTAMP WITHOUT TIME ZONE,
    yield_range_start NUMERIC(10,2),
    yield_range_end NUMERIC(10,2),
    project_id INTEGER,
    sugar_source CITEXT,
    total_sugar NUMERIC(15,5),
    yield_on_sucrose NUMERIC(15,5),
    yield_on_trs NUMERIC(15,5),
    feedstock_material_barcode CITEXT,
    trigger_time NUMERIC(10,2),
    product_id INTEGER,
    seed_vial_barcode CITEXT,
    seed_train_barcode CITEXT,
    seed_train_material CITEXT,
    calc_source_generated_date TIMESTAMP WITHOUT TIME ZONE,
    overlay_id INTEGER,
    curated_interval VARCHAR(16),
    specification_association_date TIMESTAMP WITHOUT TIME ZONE,
    specification_ab_result VARCHAR(7),
    specification_gd_result VARCHAR(7),
    mfcs_protocol_id INTEGER,
    purpose_id INTEGER,
    inoculum_amount NUMERIC(15,6),
    seed_vial_notes VARCHAR(1000),
    crystal_morphology VARCHAR(9),
    fermentation_stage_id INTEGER,
    tier VARCHAR(1),
    seed_vial_thaw_date DATE,
    intended_parent_run_id INTEGER,
    scheduled_start TIMESTAMP WITHOUT TIME ZONE,
    scheduled_tank VARCHAR(10),
    resin_id INTEGER,
    strain_id INTEGER,
    ambr_input_created_on TIMESTAMP WITHOUT TIME ZONE,
    expected_post_inoculation_volume NUMERIC(15,3),
    target_inoculum_amount NUMERIC(15,6),
    second_feedstock_material CITEXT,
    second_feedstock_material_barcode CITEXT
)
        WITH (
        OIDS=FALSE
        );

