USE [perseus]
GO
            
CREATE TABLE [hermes].[run](
[id] int IDENTITY(1, 1) NOT NULL,
[experiment_id] int NULL,
[local_id] int NULL,
[chart_legend] nvarchar(100) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[description] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[strain] nvarchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[resultant_material] varchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[feedstock_material] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fermentation_type_id] int NULL,
[start_time] datetime NULL,
[induction_time] numeric(10,2) NULL,
[induction_od] numeric(10,2) NULL,
[stop_time] numeric(10,2) NULL,
[max_yield] numeric(15,5) NULL,
[max_productivity] numeric(15,5) NULL,
[max_titer] numeric(15,5) NULL,
[total_product] numeric(15,5) NULL,
[yield_calculator_state] nvarchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productivity_method] numeric(5,1) NULL,
[productivity_notes] nvarchar(400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[peak_titer_time] numeric(10,2) NULL,
[mfcs_file] nvarchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bioreactor_label] nvarchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shaker_ids] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[platform_ids] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[media_batch_label] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overlay_batch_label] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_mfcs] datetime NULL,
[mfcs_status] varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mfcs_status_time] datetime NULL,
[mfcs_status_message] nvarchar(400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[created_on] datetime NULL,
[updated_on] datetime NULL,
[max_updated_on] datetime NULL,
[tank] nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fad_cycle] int NULL,
[creator_id] int NULL,
[updator_id] int NULL,
[max_updated_by_id] int NULL,
[protocol_id] int NULL,
[mfcs_user_id] int NULL,
[seed_vial_freeze_date] datetime NULL,
[volume_recovered] numeric(15,5) NULL,
[volume_missing] numeric(15,5) NULL,
[carbon_balance_method] numeric(5,1) NULL,
[carbon_balance] numeric(6,3) NULL,
[carbon_balance_state] nvarchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[carbon_balance_user_id] int NULL,
[carbon_balance_date] datetime NULL,
[seed_vial_id] int NULL,
[yield_published] bit NULL,
[yield_publisher_id] int NULL,
[yield_publish_date] datetime NULL,
[yield_range_start] numeric(10,2) NULL,
[yield_range_end] numeric(10,2) NULL,
[project_id] int NULL,
[sugar_source] nvarchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total_sugar] numeric(15,5) NULL,
[yield_on_sucrose] numeric(15,5) NULL,
[yield_on_trs] numeric(15,5) NULL,
[feedstock_material_barcode] varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trigger_time] numeric(10,2) NULL,
[product_id] int NULL,
[seed_vial_barcode] varchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seed_train_barcode] varchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seed_train_material] varchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[calc_source_generated_date] datetime NULL,
[overlay_id] int NULL,
[curated_interval] nvarchar(16) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[specification_association_date] datetime NULL,
[specification_AB_result] varchar(7) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[specification_GD_result] varchar(7) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[mfcs_protocol_id] int NULL,
[purpose_id] int NULL,
[inoculum_amount] numeric(15,6) NULL,
[seed_vial_notes] nvarchar(1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[crystal_morphology] varchar(9) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[fermentation_stage_id] int NULL,
[tier] varchar(1) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[seed_vial_thaw_date] date NULL,
[intended_parent_run_id] int NULL,
[scheduled_start] datetime NULL,
[scheduled_tank] nvarchar(10) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[resin_id] int NULL,
[strain_id] int NULL,
[ambr_input_created_on] datetime NULL,
[expected_post_inoculation_volume] numeric(15,3) NULL,
[target_inoculum_amount] numeric(15,6) NULL,
[second_feedstock_material] varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[second_feedstock_material_barcode] varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
ON [PRIMARY];

