-- Foreign Table: hermes.run
-- Source: SQL Server [hermes].[run]
-- Columns: 90
-- FDW Server: hermes_server

CREATE FOREIGN TABLE IF NOT EXISTS hermes.run (
    id INTEGER NOT NULL,
    experiment_id INTEGER,
    local_id INTEGER,
    chart_legend VARCHAR(100),
    description VARCHAR(255),
    strain VARCHAR(30) NOT NULL,
    resultant_material TEXT,
    feedstock_material VARCHAR(50),
    fermentation_type_id INTEGER,
    start_time TIMESTAMP,
    induction_time NUMERIC(10,2),
    induction_od NUMERIC(10,2),
    stop_time NUMERIC(10,2),
    max_yield NUMERIC(15,5),
    max_productivity NUMERIC(15,5),
    max_titer NUMERIC(15,5),
    total_product NUMERIC(15,5),
    yield_calculator_state VARCHAR(4000),
    productivity_method NUMERIC(5,1),
    productivity_notes VARCHAR(400),
    peak_titer_time NUMERIC(10,2),
    mfcs_file VARCHAR(250),
    bioreactor_label VARCHAR(30),
    shaker_ids VARCHAR(50),
    platform_ids VARCHAR(50),
    media_batch_label VARCHAR(50),
    overlay_batch_label VARCHAR(50),
    last_mfcs TIMESTAMP,
    mfcs_status VARCHAR(10),
    mfcs_status_time TIMESTAMP,
    mfcs_status_message VARCHAR(400),
    created_on TIMESTAMP,
    updated_on TIMESTAMP,
    max_updated_on TIMESTAMP,
    tank VARCHAR(20),
    fad_cycle INTEGER,
    creator_id INTEGER,
    updator_id INTEGER,
    max_updated_by_id INTEGER,
    protocol_id INTEGER,
    mfcs_user_id INTEGER,
    seed_vial_freeze_date TIMESTAMP,
    volume_recovered NUMERIC(15,5),
    volume_missing NUMERIC(15,5),
    carbon_balance_method NUMERIC(5,1),
    carbon_balance NUMERIC(6,3),
    carbon_balance_state VARCHAR(4000),
    carbon_balance_user_id INTEGER,
    carbon_balance_date TIMESTAMP,
    seed_vial_id INTEGER,
    yield_published BOOLEAN,
    yield_publisher_id INTEGER,
    yield_publish_date TIMESTAMP,
    yield_range_start NUMERIC(10,2),
    yield_range_end NUMERIC(10,2),
    project_id INTEGER,
    sugar_source VARCHAR(10),
    total_sugar NUMERIC(15,5),
    yield_on_sucrose NUMERIC(15,5),
    yield_on_trs NUMERIC(15,5),
    feedstock_material_barcode VARCHAR(50),
    trigger_time NUMERIC(10,2),
    product_id INTEGER,
    seed_vial_barcode TEXT,
    seed_train_barcode TEXT,
    seed_train_material TEXT,
    calc_source_generated_date TIMESTAMP,
    overlay_id INTEGER,
    curated_interval VARCHAR(16),
    specification_association_date TIMESTAMP,
    specification_ab_result VARCHAR(7),
    specification_gd_result VARCHAR(7),
    mfcs_protocol_id INTEGER,
    purpose_id INTEGER,
    inoculum_amount NUMERIC(15,6),
    seed_vial_notes VARCHAR(1000),
    crystal_morphology VARCHAR(9),
    fermentation_stage_id INTEGER,
    tier VARCHAR(1),
    seed_vial_thaw_date DATE,
    intended_parent_run_id INTEGER,
    scheduled_start TIMESTAMP,
    scheduled_tank VARCHAR(10),
    resin_id INTEGER,
    strain_id INTEGER,
    ambr_input_created_on TIMESTAMP,
    expected_post_inoculation_volume NUMERIC(15,3),
    target_inoculum_amount NUMERIC(15,6),
    second_feedstock_material VARCHAR(50),
    second_feedstock_material_barcode VARCHAR(50)
) SERVER hermes_server
OPTIONS (schema_name 'hermes', table_name 'run');
